### PR TITLE
Update the version of requests to latest.

### PR DESCRIPTION
**Pull request by feanil**
@e0d please review. I think you have the most context for the xqwatcher.

Changelog: https://pypi.python.org/pypi/requests

### CODE REVIEW

**Comment by feanil** [comment]
FYI: @benpatterson it looks like the xqueue-watcher doesn't have tests that get run automatically when new PRs are opened.

**Comment by feanil** [comment]
Tests passed locally.

**Comment by benpatterson** [comment]
@feanil do we need codejail for these tests? Wasn't 100% sure based on the README.

**Comment by e0d** [comment]
Looks reasonable.  I think codejail is used in the tests, but should double check.

**Comment by benpatterson** [comment]
Er, codejail has a setup cost...no idea if that's easy/hard on travis; not much experience setting up apparmor.

**Comment by e0d** [comment]
Ben I wouldn't expect the tests to leverage apparmor, but they could use the python part of cj pretty easily.

**Comment by benpatterson** [comment]
ok @e0d

**Comment by feanil** [comment]
The tests run codejail but don't seem to test apparmor.

**Pull request closed without merging**
