### PR TITLE
Use travis for CI.

### PR DESCRIPTION
**Pull request by benpatterson**

### CODE REVIEW

**Comment by benpatterson** [comment]
@feanil @e0d I gave it a quick go since I had a free cycle; however, I've got a failing test. Not sure if you're familiar enough with the codebase to help, here. Could it be related to some codejail requirements that I forgot I have on my osx machine? 

Note that the 2nd commit failed since the apparmor-utils apt package is not an approved package to install. Policy referenced here: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

**Comment by benpatterson** [comment]
@feanil @e0d if we do not use the docker image, we can install what we need for running codejail. 

Ready for your review!

**Comment by feanil** [comment]
:+1:

**Comment by benpatterson** [comment]
Squashing and merging.

**Pull request merged**
