### PR TITLE
Added docker support

### PR DESCRIPTION
**Pull request by atnartur**
Added `Dockerfile` for using xqueue-watcher inside Docker.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @atnartur! I've created [OSPR-2585](https://openedx.atlassian.net/browse/OSPR-2585) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mduboseedx** [comment]
@atnartur Thank you for the contribution! When you have a chance, could you please send in the signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can review your code going forward.

**Comment by natabene** [comment]
@atnartur Is this is something you are working on still? If so, please send us a signed contributor agreement at your earliest convenience, and we wills start reviewing your PRs. Otherwise, this PR will be closed next week.

**Comment by natabene** [comment]
@atnartur  I am closing this PR, but you are welcome to re-open it later.

**Comment by edx-webhook** [comment]
@atnartur Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue-watcher&entry.867055334=https://github.com/edx/xqueue-watcher/pull/35&entry.1484655318=https://github.com/atnartur&entry.752974735=2018-09-02+23:16&entry.1917517419=2018-11-05+19:45&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
